module.exports = {
  NOT_STARTED : 0,
  HELLO_MESSAGE_SENT: 1,
  USER_REPLIED : 2,
  GROUP_INVITATION_SENT: 3,
  GIFT_MESSAGE_SENT: 4,

  0: "NOT_STARTED",
  1: "HELLO_MESSAGE_SENT",
  2: "USER_REPLIED",
  3: "GROUP_INVITATION_SENT",
  4: "GIFT_MESSAGE_SENT"
}